version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - solar-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1})"]
      interval: 10s
      timeout: 5s
      retries: 5

  solar-system:
    image: ${DOCKER_USERNAME}/solar-system:${GITHUB_SHA}
    container_name: solar-system
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - solar-net
    environment:
      MONGO_URI: mongodb://mongo:27017/testdb

networks:
  solar-net:
    driver: bridge
