apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_USER
      remoteRef:
        key: mongo-credentials
        property: MONGO_USER
    - secretKey: MONGO_PASS
      remoteRef:
        key: mongo-credentials
        property: MONGO_PASS
    - secretKey: MONGO_DB
      remoteRef:
        key: mongo-credentials
        property: MONGO_DB
    - secretKey: MONGO_URI
      remoteRef:
        key: mongo-credentials
        property: MONGO_URI
