apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 22monk/solar-system-app:da34318b63436c9cf9fb5d6a4bb9eb9bc069b216
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017/testdb?authSource=admin"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: MONGO_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: solar-system
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 
