apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      imagePullSecrets:
        - name: regcred  # 👈 Add this to authenticate with private Docker registry
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until wget -qO- mongodb-service:27017; do echo waiting for MongoDB; sleep 5; done;']
        - name: init-db
          image: 22monk/solar-system-app:dd4431d417b6e6017a472a6450b5ab8057facd3b
          command: ["node", "/usr/app/initDB.js"]
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
      containers:
        - name: node-app
          image: 22monk/solar-system-app:dd4431d417b6e6017a472a6450b5ab8057facd3b
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: default
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
