name: Solar-system-workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
  MONGO_URI: 'mongodb://localhost:27017/testdb'

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                node-version: [18,19,20]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        services:
            mongo:
                image: mongo:latest
                ports:
                    - 27017:27017
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: Wait for MongoDB to be Ready
              run: sleep 20

            - name: Run Database Initialization Script
              run: node initDB.js

            - name: Run Unit Tests
              run: npm test
            - name: Archive test results
              uses: actions/upload-artifact@v4
              with:
                name: test-results-${{ github.run_id }}
                path: test-results-${{ github.run_id }}.xml
