name: Solar-system-workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
  MONGO_URI: 'mongodb://localhost:27017/testdb'

jobs:
    # unit-testing:
    #     name: Unit Testing
    #     strategy:
    #         matrix:
    #             node-version: [18]
    #             os: [ubuntu-latest]
    #     runs-on: ${{ matrix.os }}
    #     services:
    #         mongo:
    #             image: mongo:latest
    #             ports:
    #                 - 27017:27017
        # steps:
        #     - name: Checkout Code
        #       uses: actions/checkout@v4

        #     - name: Setup Node.js ${{ matrix.node-version }}
        #       uses: actions/setup-node@v4
        #       with:
        #         node-version: ${{ matrix.node-version }}

        #     - name: Cache Dependencies
        #       uses: actions/cache@v4
        #       with:
        #         path: node_modules
        #         key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        #     - name: Install Dependencies
        #       run: npm install

            # - name: Wait for MongoDB to be Ready
            #   run: sleep 20

            # - name: Run Database Initialization Script
            #   run: node initDB.js

            # - name: Run Unit Tests
            #   run: npm test
            # - name: Archive test results
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: test-results-${{ github.run_id }}
    #             path: test-results.xml
    # Code-Coverage:
    #     name: Code Coverage
    #     services:
    #         mongo:
    #             image: mongo:latest
    #             ports:
    #                 - 27017:27017
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Setup Nodejs 18
    #           uses: actions/setup-node@v4
            #   with: 
            #     node-version: 18

            # - name: Cache Dependencies
            #   uses: actions/cache@v4
            #   with:
            #     path: node_modules
            #     key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
                
                
            # - name: Install Dependencies
            #   run: npm install
            # - name: Wait for MongoDB to be Ready
            #   run: sleep 20
            # - name: Run Database Initialization Script
            #   run: node initDB.js
            # - name: Run Code Coverage
            #   run: npm run coverage
            # - name: Archive Coverage Report
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: coverage-${{ github.run_id }}
            #     path: coverage
            #     retention-days: 1
    Docker:
        name: login-docker
        # needs: [unit-testing, Code-Coverage]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v2.2.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: Dockerfile
                push: false
                tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{github.sha}}
            - name: Start Services with Docker Compose
              run: |
                  export DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
                  export GITHUB_SHA=${{ github.sha }}
                  docker-compose up -d
                  sleep 10  # Allow services to start
            - name: Check Running Containers
              run: docker ps -a
            
            - name: Wait for MongoDB to be Ready
              run: |
                for i in {1..10}; do
                  if docker exec $(docker ps -q -f name=mongo) mongosh --eval "db.runCommand({ping:1})" --quiet; then
                    echo "MongoDB is ready!"
                    break
                  fi
                  echo "Waiting for MongoDB..."
                  sleep 5
                done || (echo "MongoDB failed to start!" && exit 1)
            - name: Wait for Application to be Ready
              run: |
                  for i in {1..10}; do
                    curl -s http://localhost:3000/live && echo "App is live!" && break
                    echo "Waiting for the app to start..."
                    sleep 5
                  done || (echo "Application failed to start!" && exit 1)
            - name: Run Health Checks
              run: |
                    curl -X GET http://localhost:3000/ready || (echo "Ready check failed!" && exit 1)
                    curl -X GET http://localhost:3000/os || (echo "OS check failed!" && exit 1)
                    curl -X GET http://localhost:3000/ || (echo "Homepage check failed!" && exit 1)
            - name: Test Planet Endpoint
              run: |
                    curl -X POST http://localhost:3000/planet \
                        -H "Content-Type: application/json" \
                        -d '{"id": 1}' || (echo "Planet fetch failed!" && exit 1)
            - name: Stop and Clean Up
              run: docker-compose down --volumes
    